# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4054ea8f8c194c8329bf25e673f8d8277449e704386e3e6c972139f39853766675920b90e2f6e8cb3887b5856c7ee1585b9eb135b60a6f3ebc1059f5d7c97da7

test:
  secret_key_base: a80161955e4eb123be47c94657daf9a49446cd31d1b9d9f8b93f5a1d88fad93592b3c7adf03a6f86bdb5905289f2b3906692c9cc73cc8915e2b513f1d90e77a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
